from app.config import settings
from app.core.logging import logger
from app.core.graph_fallback import networkx_fallback

# Attempt to import neo4j
try:
    from neo4j import AsyncGraphDatabase
    NEO4J_AVAILABLE = True
except ImportError:
    NEO4J_AVAILABLE = False

class Neo4jService:
    def __init__(self):
        self.uri = settings.NEO4J_URI
        self.user = settings.NEO4J_USER
        self.password = settings.NEO4J_PASSWORD
        self.driver = None
        self.use_fallback = not NEO4J_AVAILABLE or settings.DEMO_MODE_FALLBACK
        
    async def connect(self):
        if self.use_fallback:
            return
            
        try:
            self.driver = AsyncGraphDatabase.driver(
                self.uri, auth=(self.user, self.password)
            )
            # Verify connection
            async with self.driver.session() as session:
                await session.run("RETURN 1")
        except Exception as e:
            logger.warning(f"Neo4j connection failed, using NetworkX fallback: {e}")
            self.use_fallback = True

    async def close(self):
        if self.driver:
            await self.driver.close()

    async def ingest_report(self, report: dict):
        if self.use_fallback:
            return networkx_fallback.ingest_report(report)
            
        # Implementation would use MERGE Cypher queries
        pass

    async def detect_clusters(self):
        if self.use_fallback:
            return networkx_fallback.get_clusters()
            
        # Implementation would use GDS or simple community detection queries
        return networkx_fallback.get_clusters() # fallback for now

    async def ego_network(self, entity_id: str):
        if self.use_fallback:
            return networkx_fallback.ego_network(entity_id)
        pass

    async def build_intel_package(self, cluster_id: str):
        cluster = await self.detect_clusters()
        # In a real app, this would generate a PDF or structured JSON with provenance
        return {
            "cluster": cluster,
            "provenance": "Generated by SentinelAI Graph Engine",
            "admissibility_hash": "mock_sha256_hash_here"
        }

neo4j_service = Neo4jService()
